# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190326_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eyes',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='face',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='lip',
            field=models.CharField(default='', max_length=255),
        ),
    ]
