# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-03-27 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190327_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AlterField(
            model_name='post',
            name='eyes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='face',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='lip',
            field=models.TextField(default=''),
        ),
    ]
