# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-01 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(1, 'public'), (2, 'private')], default='', max_length=255),
        ),
    ]
